services:
  - type: web
    name: susnata-weather-app
    env: node
    plan: free
    region: oregon
    rootDir: WeatherServer
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: API_KEY
        sync: false
      - key: APP_BASE_URL
        value: https://susnata-weather-app.onrender.com
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 465
    autoDeploy: true
    domains:
      - susnatacode.com
      - www.susnatacode.blogspot.com
